language: python
python:
  - "3.9"

before_install:
  - mysql -e "grant all privileges on *.* to 'travis'@'localhost';"

sudo: required

dist: bionic

services:
  - postgresql
  - mysql

# command to install dependencies
install: make pip

# command to run tests
script: make test
